/**
 * This config file has been generated by the gallery engine.
 *
 * You can modify this params to adjust the gallery to your needs.
 *
 * Think about that some of this are very critical. Please read the documentation.
 */
return array(
{{ params }}
);